services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT:-3308}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  image-server:
    build:
      context: ./profile_images_server
    container_name: profile-image-server
    ports:
      - "5001:5001"
    volumes:
      - ./profile_images_server/images:/app/images
    restart: always

volumes:
  mysql-data:
